dim(::Type{Polytope"2-node line"})                              = 1
dim(::Type{Polytope"3-node triangle"})                          = 2
dim(::Type{Polytope"4-node quadrangle"})                        = 2
dim(::Type{Polytope"4-node tetrahedron"})                       = 3
dim(::Type{Polytope"8-node hexahedron"})                        = 3
dim(::Type{Polytope"6-node prism"})                             = 3
dim(::Type{Polytope"5-node pyramid"})                           = 3
#dim(::Type{Polytope"3-node second order line"})                 = 2
#dim(::Type{Polytope"6-node second order triangle"})             = 2
#dim(::Type{Polytope"9-node second order quadrangle"})           = 2
#dim(::Type{Polytope"10-node second order tetrahedron"})         = 3
#dim(::Type{Polytope"27-node second order hexahedron"})          = 3
#dim(::Type{Polytope"18-node second order prism"})               = 3
#dim(::Type{Polytope"14-node second order pyramid"})             = 3
dim(::Type{Polytope"1-node point"})                             = 0
#dim(::Type{Polytope"8-node second order quadrangle"})           = 2
#dim(::Type{Polytope"20-node second order hexahedron"})          = 3
#dim(::Type{Polytope"15-node second order prism"})               = 3
#dim(::Type{Polytope"13-node second order pyramid"})             = 3
#dim(::Type{Polytope"9-node third order incomplete triangle"})   = 2
#dim(::Type{Polytope"10-node third order triangle"})             = 2
#dim(::Type{Polytope"12-node fourth order incomplete triangle"}) = 2
#dim(::Type{Polytope"15-node fourth order triangle"})            = 2
#dim(::Type{Polytope"15-node fifth order incomplete triangle"})  = 2
#dim(::Type{Polytope"21-node fifth order complete triangle"})    = 2
#dim(::Type{Polytope"4-node third order edge"})                  = 1
#dim(::Type{Polytope"5-node fourth order edge"})                 = 1
#dim(::Type{Polytope"6-node fifth order edge"})                  = 1
#dim(::Type{Polytope"20-node third order tetrahedron"})          = 3
#dim(::Type{Polytope"35-node fourth order tetrahedron"})         = 3
#dim(::Type{Polytope"56-node fifth order tetrahedron"})          = 3
#dim(::Type{Polytope"64-node third order hexahedron"})           = 3
#dim(::Type{Polytope"125-node fourth order hexahedron"})         = 3
